;; 
;; plug-format: format-all, 格式化特定语言的源代码(类似conform.nvim)
;; 
(require 'format-all)

;; 对于format-all支持的语言，在on save时，执行format格式化代码(括号里的是格式化服务器名称，需要通过外部安装，走系统包管理，或特定的包管理来安装)
(add-hook 'prog-mode-hook 'format-all-mode)

;; format-all支持格式化的语言
;; - Angular (prettier)
;; - Assembly (asmfmt)
;; - ATS (atsfmt)
;; - Awk (gawk)
;; - Bazel Starlark (buildifier)
;; - Beancount (bean-format)
;; - BibTeX (Emacs)
;; - C/C++/Objective-C (clang-format, astyle)
;; - C# (clang-format, astyle, csharpier)
;; - Cabal (cabal-fmt)
;; - Caddyfile (caddy-fmt)
;; - Clojure/ClojureScript (zprint, node-cljfmt)
;; - CMake (cmake-format)
;; - Crystal (crystal tool format)
;; - CSS/Less/SCSS (prettier, prettierd)
;; - Cuda (clang-format)
;; - D (dfmt)
;; - Dart (dartfmt, dart-format)
;; - Dhall (dhall format)
;; - Dockerfile (dockfmt)
;; - Elixir (mix format)
;; - Elm (elm-format)
;; - Emacs Lisp (Emacs)
;; - Erb (erb-format)
;; - Erlang (efmt)
;; - F# (fantomas)
;; - Fish Shell (fish_indent)
;; - Fortran Free Form (fprettify)
;; - Gleam (gleam format)
;; - GLSL (clang-format)
;; - Go (gofmt, goimports)
;; - GraphQL (prettier, prettierd)
;; - Haskell (brittany, fourmolu, hindent, ormolu, stylish-haskell)
;; - HCL (hclfmt)
;; - HTML/XHTML/XML (tidy)
;; - Hy (Emacs)
;; - Java (clang-format, astyle)
;; - JavaScript/JSON/JSX (prettier, standard, prettierd, deno)
;; - Jsonnet (jsonnetfmt)
;; - Kotlin (ktlint)
;; - LaTeX (latexindent, auctex)
;; - Ledger (ledger-mode)
;; - Lua (lua-fmt, stylua, prettier plugin)
;; - Markdown (prettier, prettierd, deno)
;; - Meson (muon fmt)
;; - Nginx (nginxfmt)
;; - Nix (nixpkgs-fmt, nixfmt, alejandra)
;; - OCaml (ocp-indent, ocamlformat)
;; - Perl (perltidy)
;; - PHP (prettier plugin)
;; - Protocol Buffers (clang-format)
;; - PureScript (purty, purescript-tidy)
;; - Python (black, isort, ruff format, yapf)
;; - R (styler)
;; - Racket (raco fmt)
;; - Reason (bsrefmt)
;; - ReScript (rescript format)
;; - Ruby (rubocop, rufo, standardrb, stree (syntax_tree))
;; - Rust (rustfmt)
;; - Scala (scalafmt)
;; - Shell script (beautysh, shfmt)
;; - Snakemake (snakefmt)
;; - Solidity (prettier plugin)
;; - SQL (pgformatter, sqlformat)
;; - Svelte (prettier plugin)
;; - Swift (swiftformat)
;; - Terraform (terraform fmt)
;; - TOML (prettier plugin, taplo fmt)
;; - TypeScript/TSX (prettier, ts-standard, prettierd, deno)
;; - V (v fmt)
;; - Vue (prettier, prettierd)
;; - Verilog (iStyle, Verible)
;; - YAML (prettier, prettierd)
;; - Zig (zig)

(provide 'plug-format)
