# [general]
working_directory = "/home/une/桌面/back/archlinux/check"

[font]
size = 12
normal.family = "SauceCodeProNerdFontCompleteMono Nerd Font"
normal.style = "SemiBold"

[shell]
program = "/usr/bin/bash"

[window]
opacity = 0.81
decorations = "None"
dynamic_title = false
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
[window.padding]
x = 0
y = 0

[colors]
primary.background = "#2c2c2c"
primary.foreground = "#dcdcdc"
normal.black       = "#3F3F3F"
normal.red         = "#FD3060"
normal.green       = "#60B48A"
normal.yellow      = "#DFAF8F"
normal.blue        = "#9AB8D7"
normal.magenta     = "#DC8CC3"
normal.cyan        = "#8CD0D3"
normal.white       = "#DCDCDC"
bright.black       = "#709080"
bright.red         = "#DCA3A3"
bright.green       = "#72D5A3"
bright.yellow      = "#16F0BB"
bright.blue        = "#94BFF3"
bright.magenta     = "#EC93D3"
bright.cyan        = "#93E0E3"
bright.white       = "#FFFFFF"

