general.working_directory = "/home/une/桌面/back/archlinux/org"


[font]
size = 12
normal.family = "SauceCodeProNerdFontCompleteMono Nerd Font"
normal.style = "SemiBold"

[terminal.shell]
program = "/usr/bin/bash"

[window]
opacity = 0.81
decorations = "None"
dynamic_title = false
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
[window.padding]
x = 0
y = 0

[colors]
primary.background = "#2c2c2c"
primary.foreground = "#dcdcdc"
normal.black       = "#3F3F3F"
normal.red         = "#FD5760"
normal.green       = "#60B48A"
normal.yellow      = "#DFAF8F"
normal.blue        = "#9AB8D7"
normal.magenta     = "#DC8CC3"
normal.cyan        = "#8CD0D3"
normal.white       = "#DCDCDC"
bright.black       = "#709080"
bright.red         = "#DCA3A3"
bright.green       = "#72D5A3"
bright.yellow      = "#16F0BB"
bright.blue        = "#94BFF3"
bright.magenta     = "#EC93D3"
bright.cyan        = "#93E0E3"
bright.white       = "#FFFFFF"

[keyboard]
bindings = [
  { mods = "Alt | Shift", key = "P", action = "ScrollPageUp" },
  { mods = "Alt | Shift", key = "N", action = "ScrollPageDown" },
  { mods = "Alt | Shift", key = "W", action = "Copy" },        
  { mods = "Alt | Shift", key = "Y", action = "Paste" },
  { mods = "Alt | Shift", key = "S", action = "SearchForward" },
  { mods = "Alt | Shift", key = "R", action = "SearchBackward" },
  { mods = "Alt | Shift", key = "V", action = "ToggleViMode" },
  { mods = "Alt | Shift", key = "G", action = "SearchCancel" },
  { mods = "Control", key = "F", mode = "Vi", action = "Right" },
  { mods = "Control", key = "B", mode = "Vi", action = "Left" },
  { mods = "Control", key = "N", mode = "Vi", action = "Down" },
  { mods = "Control", key = "P", mode = "Vi", action = "Up" },
  { mods = "Control", key = "A", mode = "Vi", action = "First" },
  { mods = "Control", key = "E", mode = "Vi", action = "Last" },
  { mods = "Control", key = "G", mode = "Vi", action = "ToggleNormalSelection" },
  { mods = "Alt", key = "F", mode = "Vi", action = "SemanticRight" },
  { mods = "Alt", key = "B", mode = "Vi", action = "SemanticLeft" },
]
