alias ls='ls --color=auto'
alias l='ls -la --color=auto'
alias ec='emacsclient -nw'
alias lse='exa --icons'
alias lst='exa --icons --tree'
alias sbr='source ~/.bashrc'
alias sbp='source ~/.bash_profile'
alias ksex='tmux kill-session'
alias kmux='tmux kill-server'
alias ff='fastfetch --load-config ~/.config/fastfetch/ff.jsonc'
alias t='tmux source-file ~/.tmux.conf'
alias rm='rm -i'
alias r='rustc'
alias grep='grep --color=auto'
alias nvi='nvim'
. "$HOME/.cargo/env"
